### PR TITLE
Update ntpmerlin.sh

### PR DESCRIPTION
**Pull request by jumpsmm7**
ADD cru_a_redirect

this will allow redirects to be enabled via cru check---- no more issues for pre-routed traffic.

### CODE REVIEW

**Comment by jumpsmm7** [comment]
this will allow redirects to be enabled via cru check---- no more issues for pre-routed traffic.

**Comment by jackyaz** [comment]
While I can merge this, I think you need to diagnose why the rules are being removed in the first place - you may have other firewall rules going astray

**Comment by jumpsmm7** [comment]
my issues happen around the time Fresh Jr script fires up. when it says it is applying IP table up and down rules. -->> atleast this is what is occuring also skynet is running too this is durring boot-up other than that it stays persistant. --> I have tried adding sleep galore to the mix and the only thing that is happening is it delays the boot up and not actually fixing the issue of the pre-routed traffic being there, but for a brief period of time i do have pre-routed traffic, then it is gone once the rest of the scripts are done running.

**Comment by jackyaz** [comment]
Have you modified FreshJR's script at all?

**Comment by jumpsmm7** [comment]
no --- plus i do not have any issues with nat traffic after FreshJR's script applies. -- i have not tested whether i lose the rule once his script applies after the 24hour check his script does.

**Comment by jumpsmm7** [comment]
System log says 
`Jun  3 15:01:33 adaptive QOS: Delayed Start Canceled

Jun  3 15:01:34 WLCEVENTD: eth1: Assoc 40:BD:32:78:17:52

Jun  3 15:01:35 adaptive QOS: Applying - Iptable Down Rules

Jun  3 15:01:35 adaptive QOS: Applying - Iptable Up   Rules (eth0)

Jun  3 15:01:35 adaptive QOS: TC Modification Delayed Start (5min)` 

Right when I lose the Pre-route off of my port forwards log.

**Comment by jumpsmm7** [comment]
this time i noticed this happened in system log once it had already been activated
Note before all this happened -- my portforward showed the pre-routed support
 `Jun  3 16:32:59 Skynet: [#] 144280 IPs (+0) -- 1630 Ranges Banned (+0) || 0 Inbound -- 0 Outbound Connections Blocked! [start] [67s]

Jun  3 16:33:00 YazFi: Firewall restarted - sleeping 60s before running YazFi

Jun  3 16:33:01 A.QoS: qos rule is less than 22

Jun  3 16:33:01 A.QoS: restart A.QoS because set_qos_conf / set_qos_on / setup rule fail

Jun  3 16:33:03 A.QoS: qos_count=2, qos_check=1

Jun  3 16:33:07 A.QoS: qos rule is less than 22

Jun  3 16:33:07 A.QoS: restart A.QoS because set_qos_conf / set_qos_on / setup rule fail

Jun  3 16:33:07 rc_service: udhcpc 1010:notify_rc start_firewall

Jun  3 16:33:07 custom_script: Running /jffs/scripts/service-event (args: start firewall)

Jun  3 16:33:08 rc_service: udhcpc 1010:notify_rc start_vpnserver1

Jun  3 16:33:08 rc_service: waitting "start_firewall" via udhcpc ...

Jun  3 16:33:08 miniupnpd[3851]: shutting down MiniUPnPd

Jun  3 16:33:09 nat: apply nat rules (/tmp/nat_rules_eth0_eth0)

Jun  3 16:33:09 custom_script: Running /jffs/scripts/nat-start

Jun  3 16:33:09 ntpMerlin: Sleeping for 5s to allow firewall/nat startup to be completed...

Jun  3 16:33:10 custom_script: Running /jffs/scripts/firewall-start (args: eth0)

Jun  3 16:33:10 miniupnpd[7896]: HTTP listening on port 54787

Jun  3 16:33:10 miniupnpd[7896]: Listening for NAT-PMP/PCP traffic on port 5351

Jun  3 16:33:10 custom_script: Running /jffs/scripts/service-event (args: start vpnserver1)

Jun  3 16:33:10 rc_service: udhcpc 1010:notify_rc start_vpnserver2

Jun  3 16:33:10 rc_service: waitting "start_vpnserver1" via udhcpc ...

Jun  3 16:33:11 kernel: tun: Universal TUN/TAP device driver, 1.6

Jun  3 16:33:11 kernel: tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>

Jun  3 16:33:11 Skynet: [%] Startup Initiated... ( skynetloc=/tmp/mnt/MY_SCRIPTS/skynet )

Jun  3 16:33:12 kernel: ADDRCONF(NETDEV_UP): tun21: link is not ready

Jun  3 16:33:12 kernel: device tun21 entered promiscuous mode

Jun  3 16:33:13 kernel: DROP IN=eth0 OUT= MAC=34:97:f6:70:16:50:00:01:5c:7d:18:46:08:00 

SRC=34.196.50.64 DST=73.192.95.94 LEN=71 TOS=0x00 PREC=0x20 TTL=231 ID=36177 DF PROTO=TCP 

SPT=9998 DPT=52679 SEQ=1216430816 ACK=3107832653 WINDOW=27872 RES=0x00 ACK PSH 

URGP=0 

Jun  3 16:33:13 ovpn-server1[8504]: OpenVPN 2.4.7 arm-unknown-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] 

[EPOLL] [MH/PKTINFO] [AEAD] built on Jun  1 2019

Jun  3 16:33:13 ovpn-server1[8504]: library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.08

Jun  3 16:33:13 ovpn-server1[8527]: WARNING: using --duplicate-cn and --client-config-dir together is 

probably not what you want

Jun  3 16:33:13 ovpn-server1[8527]: NOTE: the current --script-security setting may allow this 

configuration to call user-defined scripts

Jun  3 16:33:13 ovpn-server1[8527]: PLUGIN_INIT: POST /usr/lib/openvpn-plugin-auth-pam.so 

'[/usr/lib/openvpn-plugin-auth-pam.so] [openvpn]' intercepted=PLUGIN_AUTH_USER_PASS_VERIFY 

Jun  3 16:33:13 ovpn-server1[8527]: Diffie-Hellman initialized with 2048 bit key

Jun  3 16:33:13 ovpn-server1[8527]: Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' 

initialized with 256 bit key

Jun  3 16:33:13 ovpn-server1[8527]: Outgoing Control Channel Encryption: Using 256 bit message hash 

'SHA256' for HMAC authentication

Jun  3 16:33:13 ovpn-server1[8527]: Incoming Control Channel Encryption: Cipher 'AES-256-CTR' 

initialized with 256 bit key

Jun  3 16:33:13 ovpn-server1[8527]: Incoming Control Channel Encryption: Using 256 bit message hash 

'SHA256' for HMAC authentication

Jun  3 16:33:13 ovpn-server1[8527]: TUN/TAP device tun21 opened

Jun  3 16:33:13 ovpn-server1[8527]: TUN/TAP TX queue length set to 1000

Jun  3 16:33:13 ovpn-server1[8527]: /usr/sbin/ip link set dev tun21 up mtu 1500

Jun  3 16:33:13 kernel: ADDRCONF(NETDEV_CHANGE): tun21: link becomes ready

Jun  3 16:33:13 ovpn-server1[8527]: /usr/sbin/ip addr add dev tun21 10.8.0.1/24 broadcast 10.8.0.255

Jun  3 16:33:13 ovpn-server1[8527]: updown.sh tun21 1500 1622 10.8.0.1 255.255.255.0 init

Jun  3 16:33:13 ovpn-server1[8527]: Could not determine IPv4/IPv6 protocol. Using AF_INET6

Jun  3 16:33:13 ovpn-server1[8527]: Socket Buffers: R=[122880->122880] S=[122880->122880]

Jun  3 16:33:13 ovpn-server1[8527]: setsockopt(IPV6_V6ONLY=0)

Jun  3 16:33:13 ovpn-server1[8527]: UDPv6 link local (bound): [AF_INET6][undef]:1194

Jun  3 16:33:13 ovpn-server1[8527]: UDPv6 link remote: [AF_UNSPEC]

Jun  3 16:33:13 ovpn-server1[8527]: MULTI: multi_init called, r=256 v=256

Jun  3 16:33:13 ovpn-server1[8527]: IFCONFIG POOL: base=10.8.0.2 size=252, ipv6=0

Jun  3 16:33:13 ovpn-server1[8527]: Initialization Sequence Completed

Jun  3 16:33:14 custom_script: Running /jffs/scripts/service-event (args: start vpnserver2)

Jun  3 16:33:14 ntpMerlin: Lock file found (age: 79 seconds) - stopping to prevent duplicate runs

Jun  3 16:33:17 kernel: ADDRCONF(NETDEV_UP): tun22: link is not ready

Jun  3 16:33:17 kernel: device tun22 entered promiscuous mode

Jun  3 16:33:17 dhcp_client: bound 73.192.95.94 via 73.192.95.1 during 217901 seconds.

Jun  3 16:33:18 ovpn-server2[9218]: OpenVPN 2.4.7 arm-unknown-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] 

[EPOLL] [MH/PKTINFO] [AEAD] built on Jun  1 2019

Jun  3 16:33:18 ovpn-server2[9218]: library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.08

Jun  3 16:33:18 ovpn-server2[9284]: WARNING: using --duplicate-cn and --client-config-dir together is 

probably not what you want

Jun  3 16:33:18 ovpn-server2[9284]: NOTE: the current --script-security setting may allow this 

configuration to call user-defined scripts

Jun  3 16:33:18 ovpn-server2[9284]: PLUGIN_INIT: POST /usr/lib/openvpn-plugin-auth-pam.so 

'[/usr/lib/openvpn-plugin-auth-pam.so] [openvpn]' intercepted=PLUGIN_AUTH_USER_PASS_VERIFY 

Jun  3 16:33:18 ovpn-server2[9284]: Diffie-Hellman initialized with 2048 bit key

Jun  3 16:33:18 ovpn-server2[9284]: Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' 

initialized with 256 bit key

Jun  3 16:33:18 ovpn-server2[9284]: Outgoing Control Channel Encryption: Using 256 bit message hash 

'SHA256' for HMAC authentication

Jun  3 16:33:18 ovpn-server2[9284]: Incoming Control Channel Encryption: Cipher 'AES-256-CTR' 

initialized with 256 bit key

Jun  3 16:33:18 ovpn-server2[9284]: Incoming Control Channel Encryption: Using 256 bit message hash 

'SHA256' for HMAC authentication

Jun  3 16:33:18 ovpn-server2[9284]: TUN/TAP device tun22 opened

Jun  3 16:33:18 ovpn-server2[9284]: TUN/TAP TX queue length set to 1000

Jun  3 16:33:18 ovpn-server2[9284]: /usr/sbin/ip link set dev tun22 up mtu 1500

Jun  3 16:33:18 ovpn-server2[9284]: /usr/sbin/ip addr add dev tun22 10.16.0.1/24 broadcast 10.16.0.255

Jun  3 16:33:18 kernel: ADDRCONF(NETDEV_CHANGE): tun22: link becomes ready

Jun  3 16:33:18 ovpn-server2[9284]: updown.sh tun22 1500 1622 10.16.0.1 255.255.255.0 init

Jun  3 16:33:18 ovpn-server2[9284]: Could not determine IPv4/IPv6 protocol. Using AF_INET6

Jun  3 16:33:18 ovpn-server2[9284]: Socket Buffers: R=[122880->122880] S=[122880->122880]

Jun  3 16:33:18 ovpn-server2[9284]: setsockopt(IPV6_V6ONLY=0)

Jun  3 16:33:18 ovpn-server2[9284]: UDPv6 link local (bound): [AF_INET6][undef]:1195

Jun  3 16:33:18 ovpn-server2[9284]: UDPv6 link remote: [AF_UNSPEC]

Jun  3 16:33:18 ovpn-server2[9284]: MULTI: multi_init called, r=256 v=256

Jun  3 16:33:18 ovpn-server2[9284]: IFCONFIG POOL: base=10.16.0.2 size=252, ipv6=0

Jun  3 16:33:18 ovpn-server2[9284]: Initialization Sequence Completed

Jun  3 16:33:19 kernel: DROP IN=eth0 OUT= MAC=34:97:f6:70:16:50:00:01:5c:7d:18:46:08:00 

SRC=52.94.235.50 DST=73.192.95.94 LEN=86 TOS=0x00 PREC=0x20 TTL=224 ID=24856 DF PROTO=TCP 

SPT=443 DPT=60486 SEQ=2652146505 ACK=417624500 WINDOW=1688 RES=0x00 ACK PSH URGP=0 

`
after all this in the system log it was gone.

**Comment by jumpsmm7** [comment]
it was after all that "junk"
the additions to the script caught up and syslog showed
Jun  3 16:35:07 ntpMerlin: REACTIVATING ntpMerlin
and i got my prerouted traffic back

**Comment by jumpsmm7** [comment]
I found the issue ---- my nat-start gets triggered by some form of a loop created in all that mess-- but when it goes something inside here
            `  ntpredirect)
		
              Print_Output "true" "Sleeping for 5s to allow firewall/nat startup to be completed..." "$PASS"
		
               sleep 5
		
               Check_Lock
		
               Auto_NAT create
		
               NTP_Redirect create
		
                exit 0  `

must be preventing the route from being readded, note i completely disabled FreshJr and was getting the same issue.

**Comment by jackyaz** [comment]
I think you've found it, though not sure why it hasn't hit me. In any case, I've pushed something to master that should sort this

**Comment by jumpsmm7** [comment]
if you want you can use the re-direct option as a fail safe measure i am changing it to

`    if iptables -t nat -S | grep 123 < /dev/null 2>&1; then
       
     /jffs/scripts/ntpmerlin ntpredirect
       
     logger -t "SCRIPT_$(basename $0)" "REACTIVATING NTPMERLIN"
    fi
`
this will only do something if required.

**Comment by jumpsmm7** [comment]
if iptables -t nat -S | grep 123 > /dev/null 1>&2; then
  /jffs/scripts/ntpmerlin ntpredirect
  logger -t "SCRIPT_$(basename $0)" "REACTIVATING NTPMERLIN"
 fi

is what i ment

**Pull request closed without merging**
