### PR TITLE
Drop ipv6 NTP requests

### PR DESCRIPTION
**Pull request by maghuro**
Dirty hack

### CODE REVIEW

**Comment by jackyaz** [comment]
What's the intention, to block clients, or the router, from sending NTP queries over IPv6? The OUTPUT chain will only stop router generated NTP queries. You need to use the FORWARD chain if you want to stop clients sending the queries out on the net

**Comment by maghuro** [comment]
The intention is to block the clients from doing ntp request to the router via ipv6, because if it is an ipv6 request it'll bypass router and goes directly to the external ntp server.

**Comment by maghuro** [comment]
So, as you said, the Forward is the correct. Does the ip6tables support it?

**Comment by maghuro** [comment]
@jackyaz should the ip6tables rules on "remove" be ACCEPT or Reject as you put?

**Comment by maghuro** [comment]
I have an ntp app on android and after that commit, I can't manually (or auto) check ntp time. It gives me pool time out. However, if I disable ipv6 I'm able to pool it again

**Comment by jackyaz** [comment]
You're running the development branch. Please be prepared for things to break. If you want something that works please stop using develop and run from master which is stable.

**Comment by maghuro** [comment]
> You're running the development branch. Please be prepared for things to break. If you want something that works please stop using develop and run from master which is stable.

I'm not complaining, just telling...
My main router is using masters, this one is for testing/fun purposes...

**Comment by jackyaz** [comment]
Ok. So with IPv6 you suggested adding rules to block it, so i did. It sounds like your ntp client does not fall back to ipv4 and chooses to fail. Which app do you use, out of interest?

**Comment by maghuro** [comment]
This random one: https://play.google.com/store/apps/details?id=jp.xrea.poca.clocksync&hl=pt_PT&gl=US
Using those two ntp servers:
ntp1.tecnico.ulisboa.pt
ntp2.tecnico.ulisboa.pt

In fact, when ip6tables where in DROP it worked...

**Comment by jackyaz** [comment]
Was that when you were using the incorrect output chain?

**Comment by maghuro** [comment]
> Was that when you were using the incorrect output chain?

Correct!

**Comment by jackyaz** [comment]
> > Was that when you were using the incorrect output chain?
> 
> Correct!

that'll be why then, your rules weren't actually blocking the ipv6 attempt :)

**Comment by maghuro** [comment]
Just to clarify , my English is not so good:
When using "my" rules, it worked and got the ntp time.
After using "your" rules, that error occurred and it didn't fell back to ipv4

**Comment by jackyaz** [comment]
your rules were doing nothing, they were still allowing ipv6 as you applied to the OUTPUT chain which is for traffic coming from the router itself. it will NOT have blocked client requests.

my rules are blocking IPv6 NTP attempts, which was what you were trying to do.

**Comment by maghuro** [comment]
> your rules were doing nothing, they were still allowing ipv6 as you applied to the OUTPUT chain which is for traffic coming from the router itself. it will NOT have blocked client requests.
> 
> my rules are blocking IPv6 NTP attempts, which was what you were trying to do.

Now I understood 😁

**Pull request merged**
